get:
  operationId: getSpec
  summary: Get spec params.
  description: |
    Retrieve specification configuration used on this node.
    [Specification params list](https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/configs/mainnet/phase0.yaml)

    Values are returned with following format:
      - any value starting with 0x in the spec is returned as a hex string
      - numeric values are returned as a quoted integer
  tags:
    - Config
    - ValidatorRequiredApi
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            title: GetSpecResponse
            type: object
            properties:
              data:
                description: |
                  Key value mapping of [spec variables](https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/configs/mainnet/phase0.yaml).
                  Values are returned with following format:
                    - any value starting with 0x in the spec is returned as a hex string
                    - numeric values are returned as a quoted integer
                type: object
    "500":
      $ref: ../../beacon-node-oapi.yaml#/components/responses/InternalError
